CREATE TABLE draft_leads (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NULL,
    lead_id BIGINT NULL,
    product_key VARCHAR(50) NULL,
    agreement_number VARCHAR(100) NOT NULL,
    form_data_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
