server.port=4000
spring.datasource.url=jdbc:mysql://localhost:3308/tvs_collections
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=saibaba

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# spring.sql.init.mode=always
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
jwt.secret=ChangeThisSecretForProductionMustBeLong
jwt.expiration-ms=86400000
