server.port=4000
spring.datasource.url=jdbc:mysql://192.168.114.167:3308/tvs_collections?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata&rewriteBatchedStatements=true&cachePrepStmts=true&useServerPrepStmts=false
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=saibaba
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# spring.sql.init.mode=always
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
jwt.secret=ChangeThisSecretForProductionMustBeLong
jwt.expiration-ms=86400000
active-user.session-timeout-ms=1800000
vicidial.host=192.168.114.212
vicidial.api-user=6666
vicidial.api-pass=ckdialpro2024
vicidial.timeout-seconds=10
